# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:password@db:5432/postgres"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

volumes:
  pgdata:
